version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: build.Dockerfile
    tty: true
    working_dir: /src
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/src
      - go-mod-cache:/go/pkg
      - go-build-cache:/root/.cache/go-build

  linter:
    image: golangci/golangci-lint:v1.57.2
    working_dir: /src
    volumes:
      - ./:/src
      - go-mod-cache:/go/pkg
      - go-build-cache:/root/.cache/go-build
      - go-lint-cache:/root/.cache/golangci-lint

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  go-mod-cache:
    external: true
  go-build-cache:
    external: true
  go-lint-cache:
    external: true
